# Generated by Django 4.2.3 on 2023-08-07 05:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('dae93a77-61bf-47d3-b7e4-b5cbd82c3d75'), primary_key=True, serialize=False),
        ),
    ]
