# Generated by Django 4.2.3 on 2023-08-07 12:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_alter_review_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('8b1bf74e-99db-41c4-9cee-b9307c5f77bc'), primary_key=True, serialize=False),
        ),
    ]
