# Generated by Django 4.2.3 on 2023-08-07 13:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_alter_review_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('0f20f83f-de43-497a-9d32-ee230c938e59'), primary_key=True, serialize=False),
        ),
    ]
