# Generated by Django 4.2.3 on 2023-08-08 10:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_alter_review_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('d1c64488-6b26-4806-8f2c-b793666ad0be'), primary_key=True, serialize=False),
        ),
    ]
