# Generated by Django 4.2.3 on 2023-08-06 14:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LaundryOrder',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('transaction_amount', models.FloatField()),
                ('delivery_address', models.TextField()),
                ('owning_customer_email', models.EmailField(max_length=254)),
                ('assigned_outlet_email', models.EmailField(max_length=254)),
                ('status_id', models.UUIDField(default=uuid.uuid4)),
                ('payment_method_id', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
        migrations.CreateModel(
            name='LaundryOrderReceipt',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('subtotal', models.FloatField()),
                ('item_category_provided_id', models.UUIDField()),
                ('laundry_order_id', models.UUIDField()),
            ],
        ),
        migrations.CreateModel(
            name='LaundryProgressStatus',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
