# Generated by Django 4.2.3 on 2023-08-07 12:31
from django.db import migrations, models
from ..models import LaundryProgressStatus, PaymentMethod


def create_laundry_statuses(apps, schema_editor):
    LaundryProgressStatus.objects.create(name='pending')
    LaundryProgressStatus.objects.create(name='received')
    LaundryProgressStatus.objects.create(name='washed')
    LaundryProgressStatus.objects.create(name='dried')
    LaundryProgressStatus.objects.create(name='returned')
    PaymentMethod.objects.create(name='cash')


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laundryorder',
            old_name='delivery_address',
            new_name='pickup_delivery_address',
        ),
        migrations.RunPython(create_laundry_statuses)
    ]
